// ΠΕΡΙΛΗΨΗ + ABSTRACT
module.exports = {
  perilepsi: `Η παρούσα εργασία εξετάζει τον ρόλο της εκπαίδευσης μέσω ασκήσεων στη βελτίωση της επιχειρησιακής ετοιμότητας του Πυροσβεστικού Σώματος. Αρχικά, αναλύεται η πολυδιάστατη έννοια της επιχειρησιακής ετοιμότητας — σωματική, τεχνική, ψυχολογική, οργανωσιακή — και τα θεωρητικά θεμέλια που τεκμηριώνουν τη σημασία της πρακτικής εξάσκησης: η βιωματική μάθηση (Kolb, 1984), η στοχευμένη εξάσκηση (Ericsson, 2006) και οι μη τεχνικές δεξιότητες (Flin et al., 2008). Στη συνέχεια, παρουσιάζεται το εκπαιδευτικό σύστημα του Πυροσβεστικού Σώματος, οι τύποι ασκήσεων (επί χάρτου, πεδίου, προσομοίωσης, εξειδικευμένες) και η επίδρασή τους σε κάθε διάσταση της ετοιμότητας. Μέσα από τρία case studies — την πυρκαγιά στο Μάτι (2018), τις ασκήσεις MODEX της ΕΜΑΚ, και τις πυρκαγιές του 2021 — αναδεικνύονται τόσο τα κενά που αποκαλύφθηκαν από ανεπαρκή εκπαίδευση όσο και τα θετικά αποτελέσματα της συστηματικής εξάσκησης. Εξετάζεται ο ρόλος σύγχρονων τεχνολογιών (προσομοιωτές, VR, drones, GIS) ως συμπληρωματικών εργαλείων εκπαίδευσης. Τέλος, διατυπώνονται τεκμηριωμένες προτάσεις βελτίωσης, με έμφαση στην ενίσχυση της βιωματικής μάθησης, την αξιοποίηση τεχνολογίας, την ανάπτυξη μη τεχνικών δεξιοτήτων, τη διεύρυνση της διεθνούς συνεργασίας και την ψυχολογική υποστήριξη του προσωπικού.`,

  lekseis_kleidi: "επιχειρησιακή ετοιμότητα, εκπαίδευση πυροσβεστών, ασκήσεις, βιωματική μάθηση, Πυροσβεστικό Σώμα, πολιτική προστασία, μη τεχνικές δεξιότητες",

  abstract_en: `This thesis examines the role of exercise-based training in enhancing the operational readiness of the Hellenic Fire Service. It begins by analyzing the multidimensional concept of operational readiness — physical, technical, psychological, and organizational — and the theoretical foundations that underpin the value of practical training: experiential learning (Kolb, 1984), deliberate practice (Ericsson, 2006), and non-technical skills (Flin et al., 2008). The training system of the Hellenic Fire Service is then presented, including the types of exercises (tabletop, field, simulation, and specialized) and their impact on each dimension of readiness. Three case studies — the Mati wildfire (2018), MODEX exercises involving Greece's Special Disaster Response Unit (EMAK), and the 2021 wildfires — illustrate both the deficiencies revealed by inadequate training and the positive outcomes of systematic practice. The role of modern technologies (simulators, VR, drones, GIS) as complementary training tools is also examined. Finally, evidence-based recommendations are formulated, emphasizing enhanced experiential learning, technology integration, development of non-technical skills, expansion of international cooperation, and psychological support for personnel.`,

  keywords_en: "operational readiness, firefighter training, exercises, experiential learning, Hellenic Fire Service, civil protection, non-technical skills"
};
