// ΠΕΡΙΛΗΨΗ + ABSTRACT — BROADENED SCOPE
module.exports = {
  perilepsi: `Η παρούσα εργασία εξετάζει τον ρόλο της εκπαίδευσης μέσω ασκήσεων στη βελτίωση της επιχειρησιακής ετοιμότητας των σωμάτων ασφαλείας και των ενόπλων δυνάμεων. Η ανάλυση εκτείνεται σε τέσσερις κεντρικούς πυλώνες: το Πυροσβεστικό Σώμα, την Ελληνική Αστυνομία (με ιδιαίτερη αναφορά στην Τροχαία και τα Ειδικά Σώματα), τις Ένοπλες Δυνάμεις και τους φορείς πολιτικής προστασίας. Αρχικά, αναλύεται η πολυδιάστατη έννοια της επιχειρησιακής ετοιμότητας — σωματική, τεχνική, ψυχολογική, οργανωσιακή — και τα θεωρητικά θεμέλια που τεκμηριώνουν τη σημασία της πρακτικής εξάσκησης: η βιωματική μάθηση (Kolb, 1984), η στοχευμένη εξάσκηση (Ericsson, 2006) και οι μη τεχνικές δεξιότητες (Flin et al., 2008). Στη συνέχεια, παρουσιάζονται τα εκπαιδευτικά συστήματα κάθε σώματος, οι τύποι ασκήσεων (επί χάρτου, πεδίου, προσομοίωσης, στρατιωτικές ασκήσεις) και η επίδρασή τους σε κάθε διάσταση ετοιμότητας. Μέσα από τέσσερα case studies — την πυρκαγιά στο Μάτι (2018), τις ασκήσεις MODEX, τις στρατιωτικές ασκήσεις NATO και την εκπαίδευση της αστυνομίας σε σενάρια τρομοκρατίας — αναδεικνύονται τόσο τα κενά που αποκαλύφθηκαν από ανεπαρκή εκπαίδευση όσο και τα θετικά αποτελέσματα της συστηματικής εξάσκησης. Εξετάζεται επίσης ο ρόλος σύγχρονων τεχνολογιών (προσομοιωτές, VR, drones, GIS) ως συμπληρωματικών εργαλείων. Τέλος, διατυπώνονται τεκμηριωμένες προτάσεις βελτίωσης, με έμφαση στην ενίσχυση της βιωματικής μάθησης, τη διυπηρεσιακή εκπαίδευση, την αξιοποίηση τεχνολογίας και την ψυχολογική υποστήριξη του προσωπικού.`,

  lekseis_kleidi: "επιχειρησιακή ετοιμότητα, εκπαίδευση μέσω ασκήσεων, σώματα ασφαλείας, ένοπλες δυνάμεις, αστυνομία, πυροσβεστικό σώμα, βιωματική μάθηση, πολιτική προστασία, μη τεχνικές δεξιότητες",

  abstract_en: `This thesis examines the role of exercise-based training in enhancing the operational readiness of security forces and armed services. The analysis spans four central pillars: the Hellenic Fire Service, the Hellenic Police (with particular reference to Traffic Police and Special Units), the Armed Forces, and civil protection agencies. It begins by analyzing the multidimensional concept of operational readiness — physical, technical, psychological, and organizational — and the theoretical foundations underpinning practical training: experiential learning (Kolb, 1984), deliberate practice (Ericsson, 2006), and non-technical skills (Flin et al., 2008). The training systems of each service are then presented, along with types of exercises (tabletop, field, simulation, military drills) and their impact on each dimension of readiness. Four case studies — the Mati wildfire (2018), EU MODEX exercises, NATO military exercises, and police counter-terrorism training — illustrate both deficiencies revealed by inadequate training and positive outcomes of systematic practice. The role of modern technologies (simulators, VR, drones, GIS) as complementary training tools is also examined. Finally, evidence-based recommendations are formulated, emphasizing enhanced experiential learning, inter-agency training, technology integration, and psychological support for personnel.`,

  keywords_en: "operational readiness, exercise-based training, security forces, armed forces, police, fire service, experiential learning, civil protection, non-technical skills"
};
